title: Kaiyuan Yang's Homepage
page-top-title: Kaiyuan Yang
top-section-bg-text: There is no best but better
home-subtitle: yky666&entp;|&all kinds of sports;
copyright-text: '&copy; Kaiyuan Yang 2026. All Rights Reserved.'
